name: gcassert

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Check out code
      uses: actions/checkout@v1

    - name: Run gcassert
      run: go run github.com/jordanlewis/gcassert/cmd/gcassert
